import { registerNodes as registerArrayNodes } from "./array";
import { registerNodes as registerBooleanNodes } from "./boolean";
import { registerNodes as registerCollectionNodes } from "./collection";
import { registerNodes as registerColourNodes } from "./colour";
import { registerNodes as registerExternalNodes } from "./external";
import { registerNodes as registerFlowControlNodes } from "./flow-control";
import { registerNodes as registerFnNodes } from "./fn";
import { registerNodes as registerInputOutputNodes } from "./input-output";
import { registerNodes as registerMathNodes } from "./math";
import { registerNodes as registerMiscellaneousNodes } from "./miscellaneous";
import { registerNodes as registerNumberNodes } from "./number";
import { registerNodes as registerObjectNodes } from "./object";
import { registerNodes as registerStringNodes } from "./string";
import { registerNodes as registerUserInteractionNodes } from "./user-interaction";
import { registerNodes as registerValueNodes } from "./value";

export const registerNodes = (prefix, register, context) => {
  registerArrayNodes(`${prefix}array/`, register, context);
  registerBooleanNodes(`${prefix}boolean/`, register, context);
  registerCollectionNodes(`${prefix}collection/`, register, context);
  registerColourNodes(`${prefix}colour/`, register, context);
  registerExternalNodes(`${prefix}external/`, register, context);
  registerFlowControlNodes(`${prefix}flow-control/`, register, context);
  registerFnNodes(`${prefix}fn/`, register, context);
  registerInputOutputNodes(`${prefix}input-output/`, register, context);
  registerMathNodes(`${prefix}math/`, register, context);
  registerMiscellaneousNodes(`${prefix}miscellaneous/`, register, context);
  registerNumberNodes(`${prefix}number/`, register, context);
  registerObjectNodes(`${prefix}object/`, register, context);
  registerStringNodes(`${prefix}string/`, register, context);
  registerUserInteractionNodes(`${prefix}user-interaction/`, register, context);
  registerValueNodes(`${prefix}value/`, register, context);
};
